language: python
python:
  - "2.7"
services:
  - mongodb
  - redis-server
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
# command to install dependencies
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libldap2-dev libsasl2-dev"

install:
  - "pip install coverage"
  - "pip install python-coveralls"
  - "python setup.py -q install"
# command to run tests
script: nosetests
#after_success:
#  - coveralls

